// DOM query helpers for renderer.js.
(() => {
  const q = (selector) => document.querySelector(selector);
  const qa = (selector) => Array.from(document.querySelectorAll(selector));

  const queryDomRefs = () => ({
    shell: q('.app-shell'),
    windowMinimizeButton: q('.window-control-minimize'),
    windowMaximizeButton: q('.window-control-maximize'),
    windowCloseButton: q('.window-control-close'),
    toggle: q('.rail-toggle'),
    workbenchButton: q('.workbench-button'),
    knowledgeButton: q('.knowledge-button'),
    settingsButton: q('.settings-button'),
    errorlogsButton: q('.errorlogs-button'),
    apiSettingButton: q('.api-setting-button'),
    promptSettingButton: q('.prompt-setting-button'),
    settingsDetailGroupTitle: q('[data-settings-detail-group-title]'),
    settingsDetailButtons: qa('.settings-detail-button'),
    settingsDetailTitle: q('[data-settings-detail-title]'),
    settingsDetailDescription: q('[data-settings-detail-description]'),
    promptForm: q('.prompt-dock'),
    promptBox: q('.prompt-box'),
    promptInput: q('.prompt-input'),
    promptSend: q('.prompt-send'),
    promptPop: q('.prompt-pop'),
    promptAttach: q('.prompt-attach'),
    attachMenu: q('.attach-menu'),
    attachMenuFile: q('.attach-menu-file'),
    attachMenuRich: q('.attach-menu-rich'),
    richContextChip: q('.rich-context-chip'),
    attachmentInput: q('.attachment-input'),
    attachmentTray: q('.attachment-tray'),
    contentStream: q('.content-stream'),
    knowledgePanel: q('.assist-knowledge-list'),
    knowledgeList: q('.knowledge-list'),
    knowledgeBreadcrumb: q('.knowledge-breadcrumb'),
    knowledgeFolderBackButton: q('.knowledge-folder-back'),
    knowledgeTitleText: q('.knowledge-title-text'),
    knowledgeNewFolderButton: q('.knowledge-new-folder'),
    knowledgeDeleteModeButton: q('.knowledge-delete-mode'),
    knowledgeWideNewButton: q('.knowledge-wide-new'),
    knowledgeSearchPanel: q('.assist-knowledge-search'),
    knowledgeSearchInput: q('.knowledge-search-input'),
    knowledgeSearchClearButton: q('.knowledge-search-clear'),
    knowledgeSearchStatus: q('.knowledge-search-status'),
    knowledgeSearchResults: q('.knowledge-search-results'),
    knowledgePointMapPanel: q('.assist-knowledge-map'),
    knowledgePointMapStage: q('.assist-knowledge-map-stage'),
    knowledgePointMapToLogicButton: q('.knowledge-point-map-to-logic'),
    workbenchHistoryPanel: q('.assist-workbench-history'),
    workbenchHistoryList: q('.history-list'),
    workbenchTreePanel: q('.assist-workbench-tree'),
    workbenchGraphPanel: q('.assist-workbench-graph'),
    workbenchHistoryBackButtons: qa('.workbench-history-back'),
    workbenchHistoryClearButtons: qa('.workbench-history-clear'),
    workbenchSaveModeButton: q('.workbench-save-mode'),
    workbenchTreeList: q('.tree-list'),
    errorLogList: q('.error-log-list'),
    errorLogsContent: q('[data-errorlogs-content]'),
    graphViewport: q('.graph-viewport'),
    graphCanvas: q('.graph-canvas'),
    graphEdges: q('.graph-edges'),
    graphNodes: q('.graph-nodes'),
    apiCards: qa('.api-card'),
    apiUseButtons: qa('.api-use-button'),
    settingsPlaceholderTitle: q('[data-settings-placeholder-title]'),
    settingsPlaceholderDescription: q('[data-settings-placeholder-description]'),
    settingsContent: q('.settings-content'),
    promptDetailTitle: q('[data-prompt-detail-title]'),
    promptDetailDescription: q('[data-prompt-detail-description]'),
    promptDisplay: q('[data-prompt-display]'),
    promptEditor: q('[data-prompt-editor]'),
    promptEditButton: q('.prompt-edit-button'),
    promptResetButton: q('.prompt-reset-button'),
  });

  window.AppDom = { queryDomRefs };
})();
